apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: VAR_POD_NAME
  namespace: VAR_NAMESPACE
  labels:
    app: k8s-VAR_POD_NAME
spec:
  selector:
    matchLabels:
      app: k8s-VAR_POD_NAME
  template:
    metadata:
      labels:
        app: k8s-VAR_POD_NAME
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        # Make sure it gets scheduled on all nodes.
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      terminationGracePeriodSeconds: 30
      volumes:
        - name: VAR_POD_NAME-volume
          emptyDir: {}
        - name: time-volume
          hostPath:
            path: /etc/localtime
        - name: core-path-VAR_POD_NAME
          hostPath:
            path: /opt/VAR_PRODUCT_NAME/core-docker/VAR_SERVICE_NAME
        - name: log-VAR_SERVICE_NAME
          hostPath:
            path: /opt/VAR_PRODUCT_NAME/log/VAR_SERVICE_NAME/VAR_POD_NAME
        - name: hbp-unix-log
          hostPath:
            path: /var/run/.hbp
        - name: llf-unixlog
          emptyDir:
            medium: Memory
            sizeLimit: '1Gi'
        - name: llf-opt-log
          hostPath:
            path: /opt/unixlog
        - name: llf-system-log
          hostPath:
            path: /var/log
      #imagePullSecrets:
      #  - name: myregistrykey
      containers:
        - name: VAR_SERVICE_NAME
          image: VAR_HARBOR_ADDRESS/hbp/VAR_IMAGE_NAME:VAR_VERSION_NO
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - ls
            initialDelaySeconds: 300
            periodSeconds: 120
            timeoutSeconds: 300
            failureThreshold: 3
            successThreshold: 1
          resources:
            limits:
              memory: '200Mi'
            requests:
              memory: '100Mi'
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /data
              name: VAR_POD_NAME-volume
            - mountPath: /var/log
              name: log-VAR_SERVICE_NAME
            - mountPath: /opt/local/tmp/core
              name: core-path-VAR_POD_NAME
            - mountPath: /etc/localtime
              name: time-volume
            - mountPath: /var/run/.hbp
              name: hbp-unix-log
            - mountPath: /unix_log
              name: llf-unixlog
            - mountPath: /opt/unixlog
              name: llf-opt-log
            - mountPath: /systemlog
              name: llf-system-log
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: INTERNAL_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
